# Generated by Django 5.0.3 on 2024-03-27 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.IntegerField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=225)),
                ('student_attendence', models.IntegerField()),
                ('student_Email', models.CharField(max_length=33)),
                ('student_contactNo', models.IntegerField(max_length=10)),
                ('student_description', models.TextField()),
            ],
            options={
                'db_table': 'Student_Table',
            },
        ),
    ]
